export const ACTIONS = {
	EVENTS_FETCHED: 'EVENTS_FETCHED',
	EVENT_READED: 'EVENT_READED',
	EVENT_LIST_READY: 'EVENT_LIST_READY',
};

export const INTERVAL = 1000;

export default { ACTIONS, INTERVAL };
